
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiladorloop;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 5;
  public static final int FI = 4;
  public static final int MAS = 2;
  public static final int error = 1;
  public static final int MENOS = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "FI",
  "NUMERO"
  };
}

