
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiladorloop;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXTIENDE = 4;
  public static final int COMA = 6;
  public static final int PUNTO = 10;
  public static final int MENOS = 9;
  public static final int PUNTO_Y_COMA = 7;
  public static final int EOF = 0;
  public static final int METODOS = 15;
  public static final int CLASE = 2;
  public static final int PROPIEDADES = 14;
  public static final int IGUAL = 8;
  public static final int error = 1;
  public static final int DOS_PUNTOS = 13;
  public static final int TIPOS_PROP_MET = 12;
  public static final int CONDICIONES_LOGICAS_CUP = 11;
  public static final int TIPO_DATO_CUP = 5;
  public static final int VARIABLE_CLASE = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASE",
  "VARIABLE_CLASE",
  "EXTIENDE",
  "TIPO_DATO_CUP",
  "COMA",
  "PUNTO_Y_COMA",
  "IGUAL",
  "MENOS",
  "PUNTO",
  "CONDICIONES_LOGICAS_CUP",
  "TIPOS_PROP_MET",
  "DOS_PUNTOS",
  "PROPIEDADES",
  "METODOS"
  };
}

